name: Vue3-patch

on:
  push:
    branches: ["master", "vue3-compatibility-patch" ]
  pull_request:
    branches: ["master", "vue3-compatibility-patch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - run: npm run lint
